services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
      - db_data:/app/db
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=changeSECRET
      - ALLOWED_HOSTS=127.0.0.1,api.odt.org.pl
      - CORS_ALLOWED_ORIGINS=http://127.0.0.1:5500,https://odt.org.pl,https://api.odt.org.pl
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8001,https://odt.org.pl,https://api.odt.org.pl
      - DEBUG=1
volumes:
  static_data:
  db_data: