"""
Django settings for OtwarteDaneTransportowe project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Path to the project root on the HOST machine.
# Necessary for mounting volumes into sibling Docker containers (validation).
# Defaults to current directory if not set (for dev without env var).
HOST_PROJECT_PATH = os.environ.get('HOST_PROJECT_PATH', str(BASE_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tvfr_&a48e3=rj1djnb*572va^k=2thd07awg-ynfe(!kbx45!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Third-party
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'drf_spectacular_sidecar',

    # Local apps
    'blog.apps.BlogConfig',
    'cases.apps.CasesConfig',
    'data_manager.apps.DataManagerConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OtwarteDaneTransportowe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / 'Portal')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OtwarteDaneTransportowe.wsgi.application'

SPECTACULAR_SETTINGS = {
    'SWAGGER_UI_DIST': 'SIDECAR',  # shorthand to use the sidecar instead
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    # OTHER SETTINGS
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Dev-setup note:
# - In docker-compose Postgres is published as 5420 -> 5432 (host -> container).
# - Inside Docker network the service uses 5432.
# Containers should pass POSTGRES_HOST=postgres and POSTGRES_PORT=5432.
# Local runs (outside Docker) should use POSTGRES_HOST=127.0.0.1 and POSTGRES_PORT=5420.
USE_SQLITE = os.getenv('USE_SQLITE', '').strip().lower() in {'1', 'true', 'yes', 'on'}

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'otwarte_dane_transportowe'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
            # Default to docker-compose published port for localhost dev.
            'PORT': os.getenv('POSTGRES_PORT', '5420'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = str(BASE_DIR / 'staticfiles')

# User uploads – stored under MEDIA_ROOT but NOT served via MEDIA_URL directly.
# All downloads go through the secure Django views in data_manager/api/views.py
# which verify stage_complete_at before serving the file.
# MEDIA_URL is intentionally left with no matching URL pattern in urls.py.
MEDIA_URL = '/internal-media/'
MEDIA_ROOT = '/app/uploaded_data'

# Django REST framework
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
# Broker i backend pobieramy ze zmiennych środowiskowych — domyślnie Redis
# na localhost (dev). W docker-compose serwis nazywa się "redis".
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')

# Serializacja
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Strefa czasowa zgodna z Django
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Harmonogram — django-celery-beat przechowuje go w bazie danych
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Domyślny harmonogram (Bootstrap) — nadpisywany w bazie przez Beat Admin.
# Po pierwszym `migrate` Beat sam wypełni tabelę PeriodicTask.
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    # Feedy statyczne — sprawdzaj co minutę (download_time_1/2)
    'refresh-static-feeds': {
        'task': 'data_manager.refresh_static_feeds',
        'schedule': crontab(),          # * * * * *
        'options': {'queue': 'feeds'},
    },
    # Realtime — jednorazowy bootstrap przy starcie; potem każdy task
    # planuje siebie sam przez apply_async(countdown=endpoint.interval).
    # Uruchamiamy co 5 minut jako "watchdog" — na wypadek gdyby nowy
    # endpoint został dodany lub pętla taskowa zgasła po nieoczekiwanym błędzie.
    'bootstrap-realtime-tasks': {
        'task': 'data_manager.bootstrap_realtime_tasks',
        'schedule': crontab(minute='*/5'),   # co 5 minut
        'options': {'queue': 'feeds'},
    },
}

# Kolejki — "feeds" dla schedulingu, "default" dla reszty
CELERY_TASK_QUEUES = {
    'default': {},
    'feeds': {},
}
CELERY_TASK_DEFAULT_QUEUE = 'default'

# Maksymalny czas na wykonanie pojedynczego taska pobierania (s)
CELERY_TASK_SOFT_TIME_LIMIT = 90    # soft limit — task dostaje SoftTimeLimitExceeded
CELERY_TASK_TIME_LIMIT = 120        # hard limit — worker zabija task
