# Generated by Django 6.0.1 on 2026-01-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('transport_organization', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_providers', models.ManyToManyField(blank=True, related_name='public_transports', to='cases.dataprovider')),
            ],
            options={
                'ordering': ['region', 'transport_organization'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'None'), ('requested', 'Data Requested'), ('denial', 'Data Denial'), ('court_referral', 'Court Referral'), ('ministry_complaint', 'Complaint to the Ministry'), ('not_available', 'Data not available'), ('received', 'Data Received'), ('no_contract', 'No data contract with provider'), ('reminder', 'Reminder message'), ('phone_call', 'Phone call'), ('other', 'Other')], default='none', max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_status', to='cases.publictransport')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='publictransport',
            index=models.Index(fields=['region', 'transport_organization'], name='cases_publi_region_83d54c_idx'),
        ),
        migrations.AddConstraint(
            model_name='publictransport',
            constraint=models.UniqueConstraint(fields=('region', 'transport_organization'), name='unique_public_transport_region_org'),
        ),
        migrations.AddIndex(
            model_name='casestatus',
            index=models.Index(fields=['case', '-date'], name='cases_cases_case_id_c804d7_idx'),
        ),
    ]
