# Generated by Django 6.0.1 on 2026-01-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('transport_organization', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['region', 'transport_organization'],
            },
        ),
        migrations.RemoveIndex(
            model_name='publictransport',
            name='cases_publi_region_83d54c_idx',
        ),
        migrations.RemoveConstraint(
            model_name='publictransport',
            name='unique_public_transport_region_org',
        ),
        migrations.AddField(
            model_name='transportorganization',
            name='data_providers',
            field=models.ManyToManyField(blank=True, related_name='transport_organizations', to='cases.dataprovider'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_status', to='cases.transportorganization'),
        ),
        migrations.RemoveField(
            model_name='publictransport',
            name='data_providers',
        ),
        migrations.AddIndex(
            model_name='transportorganization',
            index=models.Index(fields=['region', 'transport_organization'], name='cases_trans_region_5b3667_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportorganization',
            constraint=models.UniqueConstraint(fields=('region', 'transport_organization'), name='unique_public_transport_region_org'),
        ),
    ]
