# Generated by Django 6.0.1 on 2026-01-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_transportorganization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicTransport',
        ),
    ]
