# Generated by Django 6.0.1 on 2026-06-21 12:24

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/', validators=[blog.validators.validate_image_file_size]),
        ),
    ]
