# Generated by Django 6.0.1 on 2026-01-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision', models.TextField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_packages', to='cases.publictransport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicFeedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_original', models.BooleanField(default=True)),
                ('data_format', models.CharField(choices=[('GTFS_RT', 'GTFS-RT'), ('SIRI', 'SIRI'), ('GBFS', 'GBFS'), ('json', 'json'), ('xml', 'xml'), ('other', 'Other')], default='other', max_length=10)),
                ('feed_type', models.CharField(blank=True, choices=[('trip_update', 'Trip Update'), ('vehicle_position', 'Vehicle Position'), ('service_alert', 'Service Alert'), ('combined_files', 'Combined files'), ('siri_sm', 'SIRI Stop Monitoring'), ('siri_vm', 'SIRI Vehicle Monitoring'), ('siri_et', 'SIRI Estimated Timetable'), ('siri_pt', 'SIRI Production Timetable'), ('siri_sx', 'SIRI Situation Exchange'), ('siri_gm', 'SIRI General Message'), ('siri_fm', 'SIRI Facility Monitoring'), ('siri_cm', 'SIRI Connection Monitoring'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feed_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_urls', to='data_manager.feedpackage')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticFeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data_manager/static_files/')),
                ('is_original', models.BooleanField(default=True)),
                ('data_format', models.CharField(choices=[('GTFS', 'GTFS'), ('NeTEx', 'NeTEx'), ('csv', 'csv'), ('json', 'json'), ('xml', 'xml'), ('other', 'Other')], default='other', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feed_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_files', to='data_manager.feedpackage')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticFeedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_original', models.BooleanField(default=True)),
                ('is_url_static', models.BooleanField(default=True)),
                ('data_format', models.CharField(choices=[('gtfs', 'GTFS'), ('netex', 'NeTEx'), ('csv', 'csv'), ('json', 'json'), ('xml', 'xml'), ('xlsx', 'xlsx'), ('other', 'Other')], default='other', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feed_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_urls', to='data_manager.feedpackage')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedpackage',
            index=models.Index(fields=['transport_organization', '-created_at'], name='data_manage_transpo_a314af_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicfeedurl',
            index=models.Index(fields=['feed_package', '-uploaded_at'], name='data_manage_feed_pa_48e155_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicfeedurl',
            index=models.Index(fields=['data_format'], name='data_manage_data_fo_123917_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicfeedurl',
            index=models.Index(fields=['feed_type'], name='data_manage_feed_ty_1c978e_idx'),
        ),
        migrations.AddIndex(
            model_name='staticfeedfile',
            index=models.Index(fields=['feed_package', '-uploaded_at'], name='data_manage_feed_pa_d69fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='staticfeedfile',
            index=models.Index(fields=['data_format'], name='data_manage_data_fo_57e9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='staticfeedurl',
            index=models.Index(fields=['feed_package', '-uploaded_at'], name='data_manage_feed_pa_38e5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='staticfeedurl',
            index=models.Index(fields=['data_format'], name='data_manage_data_fo_479d0f_idx'),
        ),
    ]
