# Generated by Django 6.0.1 on 2026-04-03 18:29

import data_manager.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_delete_publictransport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, help_text='Full JSON output from the validator, stored as a file.', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.validation_file_path)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FeedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('gtfs', 'GTFS'), ('netex', 'NeTEx'), ('gbfs', 'GBFS'), ('siri', 'SIRI'), ('gtfs_rt', 'GTFS-RT'), ('other', 'Other')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_submissions', to=settings.AUTH_USER_MODEL)),
                ('transport_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_submissions', to='cases.transportorganization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('stage_advanced', 'Stage Advanced'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20)),
                ('stage_before', models.IntegerField()),
                ('stage_after', models.IntegerField()),
                ('cause', models.TextField(blank=True, help_text='Reason for rejection — only filled for event_type=rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_history_actions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='data_manager.feedsubmission')),
            ],
            options={
                'verbose_name': 'Feed Submission History',
                'verbose_name_plural': 'Feed Submission Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('protocol', models.CharField(choices=[('gtfs_rt', 'GTFS-RT'), ('siri', 'SIRI'), ('gbfs', 'GBFS')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_entry', to='data_manager.feedsubmission')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('trip_update', 'Trip Update (GTFS-RT)'), ('vehicle_position', 'Vehicle Position (GTFS-RT)'), ('service_alert', 'Service Alert (GTFS-RT)'), ('sx', 'Situation Exchange – SX (SIRI)'), ('sm', 'Stop Monitoring – SM (SIRI)'), ('vm', 'Vehicle Monitoring – VM (SIRI)'), ('et', 'Estimated Timetable – ET (SIRI)'), ('gm', 'General Message – GM (SIRI)'), ('gbfs', 'GBFS – Main file'), ('gbfs_versions', 'GBFS Versions'), ('system_information', 'System Information'), ('vehicle_types', 'Vehicle Types'), ('station_information', 'Station Information'), ('station_status', 'Station Status'), ('free_bike_status', 'Free Bike Status'), ('system_hours', 'System Hours'), ('system_alerts', 'System Alerts')], max_length=30)),
                ('url', models.URLField()),
                ('hide_original', models.BooleanField(default=False, help_text='Server acts as a proxy and hides the original URL.')),
                ('is_original', models.BooleanField(default=False, help_text='Whether this agency is the original author of the feed.')),
                ('cached_file', models.FileField(blank=True, help_text='Server-cached copy of the feed (filled automatically).', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.realtime_feed_cached_file_path)),
                ('cached_at', models.DateTimeField(blank=True, help_text='When the cached copy was last downloaded.', null=True)),
                ('interval', models.PositiveIntegerField(help_text='Refresh interval in seconds (e.g. 30, 60). Required.')),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('auth_value', models.CharField(blank=True, help_text='API key, bearer token, or "username:password" for basic auth.', max_length=512, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='data_manager.realtimefeedentry')),
            ],
            options={
                'ordering': ['entry', 'endpoint_type'],
            },
        ),
        migrations.CreateModel(
            name='StaticFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, help_text='URL to the static feed file.', null=True)),
                ('file', models.FileField(blank=True, help_text='Static feed file uploaded directly by the user.', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.feed_file_path)),
                ('is_original', models.BooleanField(default=False, help_text='Whether this agency is the original author of the feed.')),
                ('cached_file', models.FileField(blank=True, help_text='Server-cached copy of the feed (set automatically, never by the user).', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.feed_cached_file_path)),
                ('cached_at', models.DateTimeField(blank=True, help_text='When the cached copy was last downloaded by the server.', null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('error', 'Error')], default='pending', max_length=20)),
                ('validation_message', models.TextField(blank=True, null=True)),
                ('hide_original', models.BooleanField(default=False, help_text='If checked, the server fetches the file and serves it instead of exposing the original URL.')),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('auth_value', models.CharField(blank=True, help_text='API key, bearer token, or "username:password" for basic auth.', max_length=512, null=True)),
                ('download_time_1', models.TimeField(blank=True, help_text='Time of day (UTC) to download and cache the feed.', null=True)),
                ('download_time_2', models.TimeField(blank=True, help_text='Optional second daily download time (for feeds updated twice a day).', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='static_entry', to='data_manager.feedsubmission')),
                ('validation_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_entry_report', to='data_manager.feedvalidationreport')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedFetchError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('http_error', 'HTTP Error (4xx/5xx)'), ('timeout', 'Timeout'), ('connection_error', 'Connection Error'), ('invalid_content', 'Invalid Content'), ('auth_error', 'Authentication Error')], max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, help_text='HTTP response code — filled only for error_type=http_error', null=True)),
                ('message', models.TextField(help_text='Detailed error message or exception description.')),
                ('url_attempted', models.URLField(help_text='URL from which the file was attempted to download.')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fetch_errors', to='data_manager.realtimeendpoint')),
                ('static_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fetch_errors', to='data_manager.staticfeedentry')),
            ],
            options={
                'verbose_name': 'Feed Fetch Error',
                'verbose_name_plural': 'Feed Fetch Errors',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedsubmission',
            index=models.Index(fields=['transport_organization', '-created_at'], name='data_manage_transpo_6bf392_idx'),
        ),
        migrations.AddIndex(
            model_name='feedsubmission',
            index=models.Index(fields=['data_type'], name='data_manage_data_ty_487bf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='realtimeendpoint',
            unique_together={('entry', 'endpoint_type')},
        ),
    ]
