# Generated by Django 6.0.1 on 2026-04-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeendpoint',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staticfeedentry',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], max_length=20, null=True),
        ),
    ]
