# Generated by Django 6.0.1 on 2026-01-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_transportorganization_and_more'),
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpackage',
            name='transport_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_packages', to='cases.transportorganization'),
        ),
    ]
