# Generated by Django 6.0.1 on 2026-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_alter_feedpackage_transport_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpackage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
