# Generated by GPT-5.2 on 2026-04-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('data_manager', '0003_alter_realtimeendpoint_auth_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('gtfs_rt', 'GTFS-RT'), ('siri', 'SIRI'), ('gbfs', 'GBFS')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, max_length=2048, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('static_submission', models.ForeignKey(blank=True, help_text='Published static submission this realtime depends on (required for GTFS-RT and SIRI).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtime_submissions', to='data_manager.feedsubmission')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_submissions', to=settings.AUTH_USER_MODEL)),
                ('transport_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_submissions', to='cases.transportorganization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeSubmissionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('stage_advanced', 'Stage Advanced'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20)),
                ('stage_before', models.IntegerField()),
                ('stage_after', models.IntegerField()),
                ('cause', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_history_actions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='data_manager.realtimesubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeEndpointRT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('trip_update', 'Trip Update (GTFS-RT)'), ('vehicle_position', 'Vehicle Position (GTFS-RT)'), ('service_alert', 'Service Alert (GTFS-RT)'), ('sx', 'Situation Exchange – SX (SIRI)'), ('sm', 'Stop Monitoring – SM (SIRI)'), ('vm', 'Vehicle Monitoring – VM (SIRI)'), ('et', 'Estimated Timetable – ET (SIRI)'), ('gm', 'General Message – GM (SIRI)'), ('gbfs', 'GBFS – Main file'), ('gbfs_versions', 'GBFS Versions'), ('system_information', 'System Information'), ('vehicle_types', 'Vehicle Types'), ('station_information', 'Station Information'), ('station_status', 'Station Status'), ('free_bike_status', 'Free Bike Status'), ('system_hours', 'System Hours'), ('system_alerts', 'System Alerts')], max_length=30)),
                ('url', models.URLField()),
                ('hide_original', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=False)),
                ('interval', models.PositiveIntegerField(default=60, help_text='Refresh interval in seconds.')),
                ('auth_type', models.CharField(blank=True, choices=[('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], max_length=20, null=True)),
                ('auth_value', models.CharField(blank=True, max_length=512, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='data_manager.realtimesubmission')),
            ],
            options={
                'ordering': ['submission', 'endpoint_type'],
                'unique_together': {('submission', 'endpoint_type')},
            },
        ),
        migrations.AddIndex(
            model_name='realtimesubmission',
            index=models.Index(fields=['transport_organization', '-created_at'], name='data_manage_transpo_80bfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimesubmission',
            index=models.Index(fields=['protocol'], name='data_manage_protoc_2bbd11_idx'),
        ),
        migrations.AddConstraint(
            model_name='realtimesubmission',
            constraint=models.UniqueConstraint(fields=('static_submission', 'protocol'), name='unique_realtime_protocol_per_static_submission'),
        ),
    ]

