# Generated by Django 6.0.1 on 2026-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0003_feedpackage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfeedurl',
            name='data_format',
            field=models.CharField(choices=[('gtfs_rt', 'GTFS-RT'), ('siri', 'SIRI'), ('gbfs', 'GBFS'), ('json', 'json'), ('xml', 'xml'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='staticfeedfile',
            name='data_format',
            field=models.CharField(choices=[('gtfs', 'GTFS'), ('netex', 'NeTEx'), ('csv', 'csv'), ('json', 'json'), ('xml', 'xml'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='staticfeedfile',
            name='file',
            field=models.FileField(upload_to='static_feeds/'),
        ),
    ]
