# Generated by Django 6.0.1 on 2026-01-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0004_alter_dynamicfeedurl_data_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfeedfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
