# Generated by Django 6.0.1 on 2026-03-07 11:34

import data_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0005_alter_staticfeedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfeedfile',
            name='file',
            field=models.FileField(storage=data_manager.models.OverwriteStorage(), upload_to=''),
        ),
    ]
