# Generated by Django 6.0.1 on 2026-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0005_remove_legacy_realtime_feedfetch_rt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='realtimesubmission',
            new_name='data_manage_transpo_29a0df_idx',
            old_name='data_manage_transpo_80bfb5_idx',
        ),
        migrations.RenameIndex(
            model_name='realtimesubmission',
            new_name='data_manage_protoco_dce0e5_idx',
            old_name='data_manage_protoc_2bbd11_idx',
        ),
        migrations.AlterField(
            model_name='realtimeendpointrt',
            name='cached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtimeendpointrt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='realtimesubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='realtimesubmissionhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
