# Generated by Django 6.0.1 on 2026-06-21 12:24

import data_manager.fields
import data_manager.models
import data_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_rename_data_manage_transpo_80bfb5_idx_data_manage_transpo_29a0df_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeendpointrt',
            name='auth_value',
            field=data_manager.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticfeedentry',
            name='auth_value',
            field=data_manager.fields.EncryptedCharField(blank=True, help_text='API key, bearer token, or "username:password" for basic auth. Encrypted at rest.', null=True),
        ),
        migrations.AlterField(
            model_name='staticfeedentry',
            name='file',
            field=models.FileField(blank=True, help_text='Static feed file uploaded directly by the user.', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.feed_file_path, validators=[data_manager.validators.validate_feed_file_size]),
        ),
    ]
