# Generated by Django 6.0.1 on 2026-03-12 08:04

import data_manager.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_delete_publictransport'),
        ('data_manager', '0006_alter_staticfeedfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_update_url', models.URLField(blank=True, null=True)),
                ('trip_update_hide_original', models.BooleanField(default=False)),
                ('trip_update_auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('trip_update_auth_value', models.CharField(blank=True, max_length=512, null=True)),
                ('vehicle_position_url', models.URLField(blank=True, null=True)),
                ('vehicle_position_hide_original', models.BooleanField(default=False)),
                ('vehicle_position_auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('vehicle_position_auth_value', models.CharField(blank=True, max_length=512, null=True)),
                ('service_alert_url', models.URLField(blank=True, null=True)),
                ('service_alert_hide_original', models.BooleanField(default=False)),
                ('service_alert_auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('service_alert_auth_value', models.CharField(blank=True, max_length=512, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('gtfs', 'GTFS'), ('netex', 'NeTEx'), ('gbfs', 'GBFS'), ('siri', 'SIRI'), ('gtfs_rt', 'GTFS-RT'), ('other', 'Other')], max_length=10)),
                ('feed_kind', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_upload_at', models.DateTimeField(blank=True, null=True, verbose_name='Stage 1: Data upload date')),
                ('stage_verification_at', models.DateTimeField(blank=True, null=True, verbose_name='Stage 2: Data verification date')),
                ('stage_confirmation_at', models.DateTimeField(blank=True, null=True, verbose_name='Stage 3: Admin confirmation date')),
                ('stage_complete_at', models.DateTimeField(blank=True, null=True, verbose_name='Stage 4: Upload complete date')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='URL to the static feed file.', null=True)),
                ('file', models.FileField(blank=True, help_text='Upload the static feed file directly.', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.static_feed_file_upload_to)),
                ('hide_original', models.BooleanField(default=False, help_text='If checked, the server will act as a proxy and hide the original URL.')),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('auth_value', models.CharField(blank=True, help_text='API key, bearer token, or "username:password" for basic auth.', max_length=512, null=True)),
                ('download_time_1', models.TimeField(blank=True, help_text='Time of day (UTC) to download and cache the feed.', null=True)),
                ('download_time_2', models.TimeField(blank=True, help_text='Optional second daily download time (for feeds updated twice a day).', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='dynamicfeedurl',
            name='data_manage_feed_pa_48e155_idx',
        ),
        migrations.RemoveIndex(
            model_name='dynamicfeedurl',
            name='data_manage_data_fo_123917_idx',
        ),
        migrations.RemoveIndex(
            model_name='dynamicfeedurl',
            name='data_manage_feed_ty_1c978e_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedpackage',
            name='data_manage_transpo_a314af_idx',
        ),
        migrations.RemoveIndex(
            model_name='staticfeedfile',
            name='data_manage_feed_pa_d69fb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='staticfeedfile',
            name='data_manage_data_fo_57e9eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='staticfeedurl',
            name='data_manage_feed_pa_38e5cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='staticfeedurl',
            name='data_manage_data_fo_479d0f_idx',
        ),
        migrations.AddField(
            model_name='feedsubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedsubmission',
            name='transport_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_submissions', to='cases.transportorganization'),
        ),
        migrations.AddField(
            model_name='dynamicfeedentry',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_entry', to='data_manager.feedsubmission'),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='static_entry', to='data_manager.feedsubmission'),
        ),
        migrations.RemoveField(
            model_name='dynamicfeedurl',
            name='feed_package',
        ),
        migrations.RemoveField(
            model_name='feedpackage',
            name='transport_organization',
        ),
        migrations.RemoveField(
            model_name='staticfeedfile',
            name='feed_package',
        ),
        migrations.RemoveField(
            model_name='staticfeedurl',
            name='feed_package',
        ),
        migrations.AddIndex(
            model_name='feedsubmission',
            index=models.Index(fields=['transport_organization', '-created_at'], name='data_manage_transpo_6bf392_idx'),
        ),
        migrations.AddIndex(
            model_name='feedsubmission',
            index=models.Index(fields=['data_type'], name='data_manage_data_ty_487bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='feedsubmission',
            index=models.Index(fields=['feed_kind'], name='data_manage_feed_ki_222390_idx'),
        ),
        migrations.DeleteModel(
            name='DynamicFeedUrl',
        ),
        migrations.DeleteModel(
            name='StaticFeedFile',
        ),
        migrations.DeleteModel(
            name='FeedPackage',
        ),
        migrations.DeleteModel(
            name='StaticFeedUrl',
        ),
    ]
