# Generated by Cursor on 2026-06-21

from django.db import migrations, models


FETCH_STATUS_CHOICES = [
    ('active', 'Active'),
    ('delayed', 'Delayed'),
    ('auto_paused', 'Automatically paused'),
    ('manual_paused', 'Manually paused'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0007_alter_realtimeendpointrt_auth_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticfeedentry',
            name='fetch_status',
            field=models.CharField(
                choices=FETCH_STATUS_CHOICES,
                default='active',
                help_text='Operational fetch state for proxied feeds.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='fetch_failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='next_fetch_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='fetch_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='fetch_pause_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='last_fetch_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='last_fetch_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimeendpointrt',
            name='fetch_status',
            field=models.CharField(
                choices=FETCH_STATUS_CHOICES,
                default='active',
                help_text='Operational fetch state for proxied feeds.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='realtimeendpointrt',
            name='fetch_failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realtimeendpointrt',
            name='next_fetch_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimeendpointrt',
            name='fetch_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimeendpointrt',
            name='fetch_pause_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='realtimeendpointrt',
            name='last_fetch_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimeendpointrt',
            name='last_fetch_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='staticfeedentry',
            index=models.Index(fields=['fetch_status', 'next_fetch_after'], name='data_manage_static_fetch_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeendpointrt',
            index=models.Index(fields=['fetch_status', 'next_fetch_after'], name='data_manage_rt_fetch_idx'),
        ),
    ]
