# Generated by Django 6.0.1 on 2026-03-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0007_dynamicfeedentry_feedsubmission_staticfeedentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiriFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sx_url', models.URLField(blank=True, null=True, verbose_name='Situation Exchange (SX) URL')),
                ('sx_hide_original', models.BooleanField(default=False)),
                ('sx_auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('sx_auth_value', models.CharField(blank=True, max_length=512, null=True)),
                ('sm_url', models.URLField(blank=True, null=True, verbose_name='Stop Monitoring (SM) URL')),
                ('sm_hide_original', models.BooleanField(default=False)),
                ('sm_auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('sm_auth_value', models.CharField(blank=True, max_length=512, null=True)),
                ('vm_url', models.URLField(blank=True, null=True, verbose_name='Vehicle Monitoring (VM) URL')),
                ('vm_hide_original', models.BooleanField(default=False)),
                ('vm_auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('vm_auth_value', models.CharField(blank=True, max_length=512, null=True)),
                ('et_url', models.URLField(blank=True, null=True, verbose_name='Estimated Timetable (ET) URL')),
                ('et_hide_original', models.BooleanField(default=False)),
                ('et_auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('et_auth_value', models.CharField(blank=True, max_length=512, null=True)),
                ('gm_url', models.URLField(blank=True, null=True, verbose_name='General Message (GM) URL')),
                ('gm_hide_original', models.BooleanField(default=False)),
                ('gm_auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('gm_auth_value', models.CharField(blank=True, max_length=512, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siri_entry', to='data_manager.feedsubmission')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
