# Generated by Django 6.0.1 on 2026-07-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0008_fetch_pause_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedsubmissionhistory',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Feed Submission History', 'verbose_name_plural': 'Feed Submission Histories'},
        ),
        migrations.AlterModelOptions(
            name='realtimesubmissionhistory',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
