# Generated by Django 6.0.1 on 2026-03-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0008_sirifeedentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sirifeedentry',
            name='submission',
        ),
        migrations.AlterField(
            model_name='staticfeedentry',
            name='hide_original',
            field=models.BooleanField(default=False, help_text='If checked, the server will act as a "proxy" and hide the original URL.'),
        ),
        migrations.CreateModel(
            name='RealtimeFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('gtfs_rt', 'GTFS-RT'), ('siri', 'SIRI')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_entry', to='data_manager.feedsubmission')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('trip_update', 'Trip Update (GTFS-RT)'), ('vehicle_position', 'Vehicle Position (GTFS-RT)'), ('service_alert', 'Service Alert (GTFS-RT)'), ('sx', 'Situation Exchange – SX (SIRI)'), ('sm', 'Stop Monitoring – SM (SIRI)'), ('vm', 'Vehicle Monitoring – VM (SIRI)'), ('et', 'Estimated Timetable – ET (SIRI)'), ('gm', 'General Message – GM (SIRI)')], max_length=20)),
                ('url', models.URLField()),
                ('hide_original', models.BooleanField(default=False, help_text='Server acts as a proxy and hides the original URL.')),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (user:pass)')], default='none', max_length=20)),
                ('auth_value', models.CharField(blank=True, help_text='API key, bearer token, or "username:password" for basic auth.', max_length=512, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='data_manager.realtimefeedentry')),
            ],
            options={
                'ordering': ['entry', 'endpoint_type'],
                'unique_together': {('entry', 'endpoint_type')},
            },
        ),
        migrations.DeleteModel(
            name='DynamicFeedEntry',
        ),
        migrations.DeleteModel(
            name='SiriFeedEntry',
        ),
    ]
