# Generated by Django 6.0.1 on 2026-03-12 08:34

import data_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0009_remove_sirifeedentry_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeendpoint',
            name='cached_at',
            field=models.DateTimeField(blank=True, help_text='When the cached copy was last downloaded.', null=True),
        ),
        migrations.AddField(
            model_name='realtimeendpoint',
            name='cached_file',
            field=models.FileField(blank=True, help_text='Server-cached copy of the feed (filled automatically).', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.realtime_feed_cached_upload_to),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='cached_at',
            field=models.DateTimeField(blank=True, help_text='When the cached copy was last downloaded.', null=True),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='cached_file',
            field=models.FileField(blank=True, help_text='Server-cached copy of the feed (filled automatically).', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.static_feed_cached_upload_to),
        ),
    ]
