# Generated by Django 6.0.1 on 2026-03-14 18:11

import data_manager.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0010_realtimeendpoint_cached_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedsubmission',
            name='stage_complete_at',
        ),
        migrations.RemoveField(
            model_name='feedsubmission',
            name='stage_confirmation_at',
        ),
        migrations.RemoveField(
            model_name='feedsubmission',
            name='stage_upload_at',
        ),
        migrations.RemoveField(
            model_name='feedsubmission',
            name='stage_verification_at',
        ),
        migrations.AddField(
            model_name='realtimeendpoint',
            name='interval',
            field=models.PositiveIntegerField(default=60, help_text='Refresh interval in seconds (e.g. 30, 60). Required.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimeendpoint',
            name='is_original',
            field=models.BooleanField(default=False, help_text='Whether this agency is the original author of the feed.'),
        ),
        migrations.AddField(
            model_name='realtimefeedentry',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='is_original',
            field=models.BooleanField(default=False, help_text='Whether this agency is the original author of the feed.'),
        ),
        migrations.AddField(
            model_name='staticfeedentry',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedsubmission',
            name='feed_kind',
            field=models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='realtimeendpoint',
            name='endpoint_type',
            field=models.CharField(choices=[('trip_update', 'Trip Update (GTFS-RT)'), ('vehicle_position', 'Vehicle Position (GTFS-RT)'), ('service_alert', 'Service Alert (GTFS-RT)'), ('sx', 'Situation Exchange – SX (SIRI)'), ('sm', 'Stop Monitoring – SM (SIRI)'), ('vm', 'Vehicle Monitoring – VM (SIRI)'), ('et', 'Estimated Timetable – ET (SIRI)'), ('gm', 'General Message – GM (SIRI)'), ('gbfs', 'GBFS – Main file'), ('gbfs_versions', 'GBFS Versions'), ('system_information', 'System Information'), ('vehicle_types', 'Vehicle Types'), ('station_information', 'Station Information'), ('station_status', 'Station Status'), ('free_bike_status', 'Free Bike Status'), ('system_hours', 'System Hours'), ('system_alerts', 'System Alerts')], max_length=30),
        ),
        migrations.AlterField(
            model_name='realtimefeedentry',
            name='protocol',
            field=models.CharField(choices=[('gtfs_rt', 'GTFS-RT'), ('siri', 'SIRI'), ('gbfs', 'GBFS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staticfeedentry',
            name='cached_at',
            field=models.DateTimeField(blank=True, help_text='When the cached copy was last downloaded by the server.', null=True),
        ),
        migrations.AlterField(
            model_name='staticfeedentry',
            name='cached_file',
            field=models.FileField(blank=True, help_text='Server-cached copy of the feed (set automatically, never by the user).', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.static_feed_cached_upload_to),
        ),
        migrations.AlterField(
            model_name='staticfeedentry',
            name='file',
            field=models.FileField(blank=True, help_text='Static feed file uploaded directly by the user.', null=True, storage=data_manager.models.OverwriteStorage(), upload_to=data_manager.models.static_feed_file_upload_to),
        ),
        migrations.AlterField(
            model_name='staticfeedentry',
            name='hide_original',
            field=models.BooleanField(default=False, help_text='If checked, the server fetches the file and serves it instead of exposing the original URL.'),
        ),
        migrations.CreateModel(
            name='FeedFetchError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('http_error', 'HTTP Error (4xx/5xx)'), ('timeout', 'Timeout'), ('connection_error', 'Connection Error'), ('invalid_content', 'Invalid Content'), ('auth_error', 'Authentication Error')], max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, help_text='HTTP response code — filled only for error_type=http_error', null=True)),
                ('message', models.TextField(help_text='Detailed error message or exception description.')),
                ('url_attempted', models.URLField(help_text='URL from which the file was attempted to download.')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fetch_errors', to='data_manager.realtimeendpoint')),
                ('static_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fetch_errors', to='data_manager.staticfeedentry')),
            ],
            options={
                'verbose_name': 'Feed Fetch Error',
                'verbose_name_plural': 'Feed Fetch Errors',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('stage_advanced', 'Stage Advanced'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20)),
                ('stage_before', models.IntegerField()),
                ('stage_after', models.IntegerField()),
                ('cause', models.TextField(blank=True, help_text='Reason for rejection — only filled for event_type=rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_history_actions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='data_manager.feedsubmission')),
            ],
            options={
                'verbose_name': 'Feed Submission History',
                'verbose_name_plural': 'Feed Submission Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]

