# Generated by Copilot on 2026-03-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0011_remove_feedsubmission_stage_complete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfeedentry',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_entries', to='data_manager.feedsubmission'),
        ),
    ]

